stages:
  - test
  - doc

test:mipy:
  stage: test
  tags:
    - linux
  image: python:3.7
  interruptible: true
  script:
    - 'pip install --upgrade mypy pytest types-requests'
    - 'pip install --upgrade -r requirements.txt'
    - 'mypy updater'
  only:
    - branches@manuelcortez/updater
    - release
    - tags
    - schedules

test:pytest:
  stage: test
  tags:
    - linux
  image: python:3.8
  interruptible: true
  script:
    - 'pip install --upgrade pytest coverage requests_mock'
    - 'pip install --upgrade -r requirements.txt'
    - 'coverage run --source . --omit conf.py -m pytest --junitxml=report.xml'
    - 'coverage report'
    - 'coverage xml'
  only:
    - branches@manuelcortez/updater
    - release
    - tags
    - schedules
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml

pages:
  image: python:latest
  tags:
    - docker
  interruptible: true
  only:
    - master
  stage: doc
  script:
    - 'pip install --upgrade sphinx'
    - 'make html'
    - 'mv -f _build/html public'
  artifacts:
    expire_in: 1 day
    paths:
      - public